### ISSUE TITLE
"User not found" message when blocking domains

### ISSUE THREAD

**Issue by RaitaroH** [u-Kuro/Kanshi.Anime-Recommendation#1]
If you are blocking the third-party domains on your site, you will get a message of "user not found".
Makes sense.

I believe it should be better to say something like:
"User not found. Either make an account or ensure you are not blocking 3rd party domains". or something like that.

**Comment by u-Kuro** [comment]
Sorry, had taken a bit long to reply. Since the landing page now shows general suggestions without requiring an AniList username, i'll be closing this issue as no longer relevant.

**Comment by u-Kuro** [comment]
Sorry, had taken a bit long to reply. Since the landing page now shows general suggestions without requiring an AniList username, i'll be closing this issue as no longer relevant.
