### ISSUE TITLE
can some one help me , i cant find where is APIs code in this project , 

### ISSUE THREAD

**Issue by shimasekai** [u-Kuro/Kanshi.Anime-Recommendation#3]
cant find where is APIs code in this project ,  this project as description must use YouTube and anilist APIs but i cant find where is code for APIs or APIs key or any API related ... there is no config.js or .env ... please can someone tell me what i am missing or what is problem

**Comment by u-Kuro** [comment]
There's no API for the site itself, if that's what you're asking?

Its only a static web app that uses free YouTube and AniList APIs to get the data and saved in your web browser using [IndexedDB](https://developer.mozilla.org/en-US/docs/Web/API/IndexedDB_API/Using_IndexedDB) 

For YouTube, its just the [IFrame Player API](https://developers.google.com/youtube/iframe_api_reference)

You can find the code for using AniList API below but its minified:
- [Getting User List in AniList](https://github.com/u-Kuro/Kanshi-Anime-Recommender/blob/main/docs/web-worker/requestMediaEntries.js) 
- [Getting Media in AniList](https://github.com/u-Kuro/Kanshi-Anime-Recommender/blob/main/docs/web-worker/requestUserEntries.js)
